### PR TITLE
Catching localStorage errors

### PR DESCRIPTION
**Pull request by stulees**
- Catching and logging a warning in console when `localStorage.setItem()` fails
- Catching and logging a warning in console when `localStorage.removeItem()` fails
- Adding mock of `localStorage` and revised and added unit tests on code involving `localStorage`
- Version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review. This includes a mock of `localStorage` and revised and additional tests regarding use of `localStorage`. Thanks

**Comment by donnapep** [comment]
@stulees I'm assuming that you ran `gulp bump` and it bumped the version to 1.1.0? I think it should actually be 1.0.2 since it's just a bug fix. Forgot to mention this on the last one.

Also, I think the mock needs to be in `widget-tester` repo so that it can be reused.

Thx.

**Comment by stulees** [comment]
@donnapep I actually manually bumped the version cause I wanted `1.1.0`. A gulp bump would have put it to `1.0.2`. What's our protocol the for versioning? I wanted `1.1.0` because it's a more stable version (given the bug fix). 

re: widget tester, good idea. I'll do that and revise this PR.

**Comment by donnapep** [comment]
@stulees I always assumed we were using [semantic versioning](http://semver.org/). [This guy](https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e) doesn't like it, but doesn't provide any alternative, so I think we should use semver or else we have to come up with our own versioning strategy.

**Comment by stulees** [comment]
@donnapep As we discussed, I've bumped version to `1.0.2` and now using the newly added mock from widget-tester.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
