### PR TITLE
Infrastructure and base files

### PR DESCRIPTION
**Pull request by stulees**
- Used polymer generator
- Prepped component and test files with base code
- Added editor configuration files
- Added web component test config file
- Added CCI file
- README without component usage or attributes documentation

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks.
@rodrigopavezi Have a look to the `circle.yml` file. I've ensured installation of yeoman and generator-polymer occur in dependencies/pre. Then I've added your script for automating the deployment to the GH page in deployment/production/commands after it runs the build. Let me know if you think anything needs changing or adding.

**Comment by donnapep** [comment]
:+1:

**Comment by rodrigopavezi** [comment]
@stulees I started playing with it on the https://github.com/Rise-Vision/rise-apis. It is not working at, there are something to be done. Currently it is asking for the git authentication (https://circleci.com/gh/Rise-Vision/rise-apis/9). So I reckon you should leave it for now and add it later after I get it working properly.

cheers

**Comment by stulees** [comment]
@rodrigopavezi I've removed the configuration in `circle.yml` of deploying the GH page. Will address this in a later PR when you've resolved how to do it in rise-apis. Thanks! @donnapep FYI

**Pull request merged**
