### PR TITLE
Adding support for date ranges

### PR DESCRIPTION
**Pull request by stulees**
- Using `moment.js` for Date validation and formatting
- Providing attributes for setting a range on start and end dates to filter response by
- Enforcing ISO 8601 `YYYY-MM-DD` format for range attributes values
- Demo applying an end date

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review. Note, trying to figure out the mocking of the calendar api via `<google-client-loader>` is still on my radar, will address in one of my further PRs towards development of this component. Thanks

**Comment by donnapep** [comment]
@stulees Should there be tests for checking that `params.timeMin` and `params.timeMax` are set correctly?

**Comment by stulees** [comment]
@donnapep Have added a test in the `_getParams()` suite, rebased, thanks.

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
